services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
    networks:
      - nest-starter-net
    depends_on:
      - postgres

  postgres:
    image: 'bitnami/postgresql:17'
    restart: always
    environment:
      POSTGRESQL_PORT_NUMBER: ${DB_PORT}
      POSTGRESQL_USERNAME: ${DB_USER}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      POSTGRESQL_DATABASE: ${DB_NAME}
      POSTGRESQL_TIMEZONE: 'Asia/Tashkent'
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - nest-starter-net
    volumes:
      - nest-starter-postgres-data:/bitnami/postgresql

volumes:
  nest-starter-postgres-data:
    driver: local

networks:
  nest-starter-net:
    driver: bridge
