export enum EnvVars {
  PORT = 'PORT',
  SWAGGER = 'SWAGGER',
  CORS = 'CORS',
  JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET',
  JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
  DB_USER = 'DB_USER',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',
  DB_PORT = 'DB_PORT',
  DB_HOST = 'DB_HOST',
}
