export enum EnvVars {
  PORT = 'PORT',
  SWAGGER = 'SWAGGER',
  CORS = 'CORS',
  REDIS_PASSWORD = 'REDIS_PASSWORD',
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_DB = 'REDIS_DB',
}
